variables_base:
  - name: AGE
    type: number
    min: 18
    max: 100
  - name: SEXE
    type: categorie
    options: [M, F]
    
variables_medicales:
  - name: Metastases
    type: bool
  - name: Adenopathie
    type: bool
    condition: "Metastases == True"
